### ISSUE TITLE
"Vid2RVID.exe" produces a 1KB file when .mp4 file is 16.9MB.

### ISSUE THREAD

**Issue by stampylongr** [RocketRobz/Vid2RVID#2]
Hello,
I was trying to convert an .mp4 file to your .rvid format and all I got was an unplayable 1KB .rvid file (I tested it in RocketVideoPlayer).

Am I doing anything wrong, or is there a problem with the software?

**Comment by RocketRobz** [comment]
In `rvidFrames`, what are the first few frame files called?
