### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Urielgamer012** [RocketRobz/Vid2RVID#3]
How can I convert or transform an mp4 file to rvid because I do not know how to do it and I need help if you help me I would appreciate it

**Comment by RocketRobz** [comment]
This repo's wiki will tell you how to do it.

**Comment by Urielgamer012** [comment]
Oh thanks

**Comment by Urielgamer012** [comment]
And where is it that I'm new and I do not know I'm dumb

**Comment by Urielgamer012** [comment]
oh lo siento es que estoy en android y no me aperecia 
Lo siento

**Comment by Urielgamer012** [comment]
oh lo siento es que estoy en android y no me aperecia 
Lo siento

**Comment by Urielgamer012** [comment]
oh i'm sorry i'm on android and it did not appeal to me Sorry

**Comment by RocketRobz** [comment]
https://github.com/RocketRobz/Vid2RVID/wiki/Converting-a-video-to-.rvid

**Comment by Urielgamer012** [comment]
thanks
