### ISSUE TITLE
having trouble with convertion

### ISSUE THREAD

**Issue by hello-kale** [RocketRobz/Vid2RVID#4]
Hello mr rocket! Im trying to get a couple of random videos to play on your rocket player but the screenshot you provided in step 14 of extarcting the video frames on your convertion walkthrough was very hard to decipher because of the resolution. I would like to know what the first feild: "filename prefix" said. If that was not the issue then I would like your professional opinion on what the problem might be, the video starts playing but it's just random static. If the filename prefix of the images are irellevant then what might the problem be?

**Comment by RocketRobz** [comment]
The first frame must be named `frame0.png`, not `frame00.png` or `frame000.png` etc.

**Comment by hello-kale** [comment]
Thank you so much for your time and help

**Comment by RocketRobz** [comment]
You're welcome!
