### ISSUE TITLE
Make the pictures bigger in the tutorial

### ISSUE THREAD

**Issue by GlazedBelmont** [RocketRobz/Vid2RVID#5]
The ideal settings picture's resolution is super low that we cant even recognize any word

**Comment by Kodtiz3D** [comment]
Screenshot in question
 ![](https://camo.githubusercontent.com/16adfe5629910e1e1ed8712fdfb191037cf3be13/68747470733a2f2f67626174656d702e622d63646e2e6e65742f646174612f6174746163686d656e74732f3136372f3136373230382d30373138393963656230313438366638363061623166333138663763613430392e6a7067)
Referenced in step 15 of https://github.com/RocketRobz/Vid2RVID/wiki/Converting-a-video-to-.rvid#extracting-the-video-frames
EDIT: Wrong instruction step used

**Comment by RocketRobz** [comment]
Fixed.
The thumbnail version was accidentally used. :P
