### ISSUE TITLE
Can not open the mp4 file in Audacity

### ISSUE THREAD

**Issue by jacobhash** [RocketRobz/Vid2RVID#6]
I can not open the mp4 in Audacity, it says i need some ffmpeg library to open it, what should i do

**Comment by RocketRobz** [comment]
Install the latest version of Audacity. It includes the FFMPEG library.

**Comment by jacobhash** [comment]
Another problem, i managed to get the audio thing set up, but the exported file when playing it in the player it shows static and not the actual video.

**Comment by RocketRobz** [comment]
In `rvidFrames`, what's the first .png file called?

**Comment by jacobhash** [comment]
frame0000, wait i think i know whats wrong, it needs to be frame0, doesnt it

**Comment by RocketRobz** [comment]
Yes.

**Comment by jacobhash** [comment]
Can not find out how to make it export the first file as frame0, i am using latest version of virtualdub2, I could not find an earlier version.

**Comment by RocketRobz** [comment]
There's an earlier version linked here: https://github.com/RocketRobz/Vid2RVID/wiki/Converting-a-video-to-.rvid
If you already using it, just change minimum number of digits in name, to `1`.

**Comment by jacobhash** [comment]
Yes, it works now!, i didnt set up the audio like you did, i opened the video in virtualdub and exported it as a audio file then went to audacity
